### ISSUE TITLE
Change the fork hierarchy, have EuroCRIS/CERIF-TG-Tools on top

### ISSUE THREAD

**Issue by jdvorak001** [EuroCRIS/CERIF-TG-Tools#12]
The present hierarchy 

- @abollini / [CERIF-TG-Tools](https://github.com/abollini/CERIF-TG-Tools)
  - @jdvorak001 / [CERIF-TG-Tools](https://github.com/jdvorak001/CERIF-TG-Tools)
    - @chenejac / [CERIF-TG-Tools](https://github.com/chenejac/CERIF-TG-Tools)
    - @EuroCRIS / [CERIF-TG-Tools](https://github.com/EuroCRIS/CERIF-TG-Tools)
      - @lremy / [CERIF-TG-Tools](https://github.com/lremy/CERIF-TG-Tools)

should be changed to

- @EuroCRIS / [CERIF-TG-Tools](https://github.com/EuroCRIS/CERIF-TG-Tools)
  - @abollini / [CERIF-TG-Tools](https://github.com/abollini/CERIF-TG-Tools)
  - @chenejac / [CERIF-TG-Tools](https://github.com/chenejac/CERIF-TG-Tools)
  - @jdvorak001 / [CERIF-TG-Tools](https://github.com/jdvorak001/CERIF-TG-Tools)
  - @lremy / [CERIF-TG-Tools](https://github.com/lremy/CERIF-TG-Tools)

**Comment by jdvorak001** [comment]
Would there perhaps be a less desctructive way than asking @abollini, @chenejac and myself (@jdvorak001) to delete and re-create our repos?

**Comment by jdvorak001** [comment]
My help + forums search did not reveal anything more clever.
Since all our repos are in sync now, I'll delete & re-create my repo and we'll see what happens. I won't touch this one though.

**Comment by jdvorak001** [comment]
By deleting my repo, the forks from my repo got promoted to forks of @abollini's.

**Comment by abollini** [comment]
Hi @jdvorak001,
it is fine to me to transfer the ownership of the repository to the EuroCRIS organisation. So according to the https://help.github.com/en/github/administering-a-repository/transferring-a-repository instructions I expect that you need to delete the fork from the EuroCRIS organisation so that I can send you the transfer request

**Comment by jdvorak001** [comment]
Hi @abollini,

I'm afraid transferring ownership has two obstacles, namely the following two bullet points from [the page you referenced](https://help.github.com/en/github/administering-a-repository/transferring-a-repository):

- To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization.
- The target account must not have a repository with the same name, or a fork in the same network.

The first one could be overcome, but the latter would require the whole hierarchy to be rebuilt again.

Currently we are having:

- @abollini / [CERIF-TG-Tools](https://github.com/abollini/CERIF-TG-Tools)
  - @chenejac / [CERIF-TG-Tools](https://github.com/chenejac/CERIF-TG-Tools)
  - @EuroCRIS / [CERIF-TG-Tools](https://github.com/EuroCRIS/CERIF-TG-Tools)
    - @jdvorak001 / [CERIF-TG-Tools](https://github.com/jdvorak001/CERIF-TG-Tools)
    - @lremy / [CERIF-TG-Tools](https://github.com/lremy/CERIF-TG-Tools)

If you could delete your repo and fork @EuroCRIS / [CERIF-TG-Tools](https://github.com/EuroCRIS/CERIF-TG-Tools) again, it would be just @chenejac left, who is ready to do the same.

I know this is a bit unusual, but it appears to be the quickest path towards the goal. I already deleted and re-forked mine, and it is perfectly functional afterwards. Your commits — which have paved the very beginnings this repo — will be preserved, no worry about that.

**Comment by abollini** [comment]
done, it seems that everything is ok

**Comment by jdvorak001** [comment]
Thank you, @abollini! 
We now have the desired state (see the first comment).
