### ISSUE TITLE
Dates on ResultPatents

### ISSUE THREAD

**Issue by jdvorak001** [EuroCRIS/CERIF-TG-Tools#16]
https://github.com/openaire/guidelines-cris-managers/issues/88 ->
1. Change the reference to the CERIF data model, use the start dates on the relevant classifications rather than the deprecated ApprovalDate and RegistrationDate attributes
2. Add documentation for `<ApprovalDate>` and `<RegistrationDate>`
3. Add the requested `<PublicationDate>` element

**Comment by abollini** [comment]
@jdvorak001 this PR https://github.com/openaire/guidelines-cris-managers/pull/89 should be in the agreed direction, can you help to finalize it?
